metadata:
  labels:
    app: examples
    description: Examples Controller
    title: Quickstart service demo
spec:
  deploy:
    apiFileName: zhuquing-openapi-v3.yaml
    type:
      fwkSpringBoot:
        groupId: com.mercadona.pruebat.web-demo
        artifactId: examples-api
        package: com.mercadona.pruebat.api.web-demo
        interfacesWithTags: false
