spring:
  flyway:
    locations: classpath:migration/versions

  datasource:
    url: jdbc:postgresql://db_postgres_pruebate:5432/examples
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
fwkcna:
  jpa:
    data-migration:
      disabled: false
